# Site settings
title: InFeIM's Step-up
description: >
  대 AI 시대에 '충분한 난폭함이 있기에, 내 삶을 시련으로 만들리라' 라는 좌우명으로 도전해봅니다.
  과연 이 도전의 끝에 무엇이 있을지...

baseurl: "https://infeimkr.github.io/" # the subpath of your site, e.g. /blog/
url: "https://infeimkr.github.io/" # the base hostname & protocol for your site

author:
  fullname: Lim InCheol
  # googleplus: https://www.google.com/+MotaquillahMaddane
  github: infeimkr
  twitter: InFeIM
  # disqus: your_disqus_forum_shortname

# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown

plugins:
  - jekyll-sitemap
